/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pousada.interface_grafica;


import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import pousada.gerenciador_tarefas.GerenciadorInterfaceGrafica;


/**
 *
 * @author Aluno
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    GerenciadorInterfaceGrafica gerenciadorInterfaceGrafica;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        URL url = this.getClass().getResource("/pousada/interface_grafica/imagens/logo-mobile.png"); 
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url); 
        this.setIconImage(iconeTitulo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        imagemLabel = new javax.swing.JLabel();
        imagemLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        quartos = new javax.swing.JMenu();
        jMenuCadHosp = new javax.swing.JMenuItem();
        jMenuConsHosp = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadQuarto = new javax.swing.JMenuItem();
        jMenuConsQuarto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuCadReserv = new javax.swing.JMenuItem();
        jMenuConsReserv = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuOcuQuartos = new javax.swing.JMenuItem();
        jMenuFaturamento = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pousada Recanto Al Mare");

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jDesktopPane1.setOpaque(false);
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1280, 720));

        imagemLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pousada/interface_grafica/imagens/logo-mobile (1).png"))); // NOI18N

        imagemLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagemLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pousada/interface_grafica/imagens/logo-mobile (1).png"))); // NOI18N

        jDesktopPane1.setLayer(imagemLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(imagemLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(imagemLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemLabel)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(imagemLabel1)
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagemLabel)
                .addContainerGap())
        );

        quartos.setText("Hóspedes");
        quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartosActionPerformed(evt);
            }
        });

        jMenuCadHosp.setText("Cadastrar Hóspede");
        jMenuCadHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadHospActionPerformed(evt);
            }
        });
        quartos.add(jMenuCadHosp);

        jMenuConsHosp.setText("Consultar Hóspede");
        jMenuConsHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsHospActionPerformed(evt);
            }
        });
        quartos.add(jMenuConsHosp);

        jMenuBar1.add(quartos);

        jMenu1.setText("Quartos");

        jMenuCadQuarto.setText("Cadastrar Quarto");
        jMenuCadQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadQuartoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadQuarto);

        jMenuConsQuarto.setText("Consultar Quarto");
        jMenuConsQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsQuartoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuConsQuarto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservas");

        jMenuCadReserv.setText("Cadastrar Reserva");
        jMenuCadReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadReservActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCadReserv);

        jMenuConsReserv.setText("Consultar Reserva");
        jMenuConsReserv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsReservActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuConsReserv);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Consultas");

        jMenuOcuQuartos.setText("Ocupação dos Quartos");
        jMenuOcuQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOcuQuartosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuOcuQuartos);

        jMenuFaturamento.setText("Faturamento");
        jMenuFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFaturamentoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuFaturamento);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartosActionPerformed

    }//GEN-LAST:event_quartosActionPerformed

    private void jMenuCadQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadQuartoActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getCadastrarQuartos();
    }//GEN-LAST:event_jMenuCadQuartoActionPerformed

    private void jMenuCadHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadHospActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getCadastrarCliente();
    }//GEN-LAST:event_jMenuCadHospActionPerformed

    private void jMenuConsHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsHospActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getConsultarCliente();
    }//GEN-LAST:event_jMenuConsHospActionPerformed

    private void jMenuConsQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsQuartoActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getConsultarQuarto();
    }//GEN-LAST:event_jMenuConsQuartoActionPerformed

    private void jMenuCadReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadReservActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getCadastrarReserva();
    }//GEN-LAST:event_jMenuCadReservActionPerformed

    private void jMenuConsReservActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsReservActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getConsultarReserva();
    }//GEN-LAST:event_jMenuConsReservActionPerformed

    private void jMenuOcuQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOcuQuartosActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getQuarDis();
    }//GEN-LAST:event_jMenuOcuQuartosActionPerformed

    private void jMenuFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFaturamentoActionPerformed
        gerenciadorInterfaceGrafica = GerenciadorInterfaceGrafica.getInstancia();
        gerenciadorInterfaceGrafica.getFaturamento();
    }//GEN-LAST:event_jMenuFaturamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagemLabel;
    private javax.swing.JLabel imagemLabel1;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadHosp;
    private javax.swing.JMenuItem jMenuCadQuarto;
    private javax.swing.JMenuItem jMenuCadReserv;
    private javax.swing.JMenuItem jMenuConsHosp;
    private javax.swing.JMenuItem jMenuConsQuarto;
    private javax.swing.JMenuItem jMenuConsReserv;
    private javax.swing.JMenuItem jMenuFaturamento;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuOcuQuartos;
    private javax.swing.JMenu quartos;
    // End of variables declaration//GEN-END:variables
}
